/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/criptomonedas`; params?: Router.UnknownInputParams; } | { pathname: `/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tarjetas`; params?: Router.UnknownInputParams; } | { pathname: `/transacciones`; params?: Router.UnknownInputParams; } | { pathname: `/transferencias`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/operaciones` | `/operaciones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portafolio` | `/portafolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pagos` | `/pagos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/criptomonedas`; params?: Router.UnknownOutputParams; } | { pathname: `/cuentas`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/tarjetas`; params?: Router.UnknownOutputParams; } | { pathname: `/transacciones`; params?: Router.UnknownOutputParams; } | { pathname: `/transferencias`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/operaciones` | `/operaciones`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/portafolio` | `/portafolio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pagos` | `/pagos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/criptomonedas${`?${string}` | `#${string}` | ''}` | `/cuentas${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/tarjetas${`?${string}` | `#${string}` | ''}` | `/transacciones${`?${string}` | `#${string}` | ''}` | `/transferencias${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/operaciones${`?${string}` | `#${string}` | ''}` | `/operaciones${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/portafolio${`?${string}` | `#${string}` | ''}` | `/portafolio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pagos${`?${string}` | `#${string}` | ''}` | `/pagos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/criptomonedas`; params?: Router.UnknownInputParams; } | { pathname: `/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tarjetas`; params?: Router.UnknownInputParams; } | { pathname: `/transacciones`; params?: Router.UnknownInputParams; } | { pathname: `/transferencias`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/operaciones` | `/operaciones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portafolio` | `/portafolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pagos` | `/pagos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
    }
  }
}
